package th.ac.ku.kps.eng.cpe.soa.driveCar.model;
// Generated Apr 21, 2019 5:30:45 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	@JsonIgnore
	private String password;
	private String fname;
	private String lname;
	private String address;
	private String phoneNumber;
	private String typeUser;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
//	@OneToMany(cascade = CascadeType.ALL,mappedBy = "user")
	@JsonBackReference
	private Set companies = new HashSet(0);
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@OneToMany(cascade = CascadeType.ALL,mappedBy = "user")
	@JsonBackReference
	private Set rents = new HashSet(0);

	public User() {
	}

	public User(String username, String password, String fname, String lname, String phoneNumber, String typeUser) {
		this.username = username;
		this.password = password;
		this.fname = fname;
		this.lname = lname;
		this.phoneNumber = phoneNumber;
		this.typeUser = typeUser;
	}

	public User(String username, String password, String fname, String lname, String address, String phoneNumber,
			String typeUser, Set companies, Set rents) {
		this.username = username;
		this.password = password;
		this.fname = fname;
		this.lname = lname;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.typeUser = typeUser;
		this.companies = companies;
		this.rents = rents;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getTypeUser() {
		return this.typeUser;
	}

	public void setTypeUser(String typeUser) {
		this.typeUser = typeUser;
	}

	public Set getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set companies) {
		this.companies = companies;
	}

	public Set getRents() {
		return this.rents;
	}

	public void setRents(Set rents) {
		this.rents = rents;
	}

}
